module.exports = {
  singleQuote: true,
  jsxSingleQuote: true,
  printWidth: 120,
  jsxBracketSameLine: true,
  trailingComma: 'all',
  arrowParens: 'always',
  endOfLine: 'lf',
  tabWidth: 2,
  semi: true,
  quoteProps: 'as-needed',
  bracketSpacing: true,
  htmlWhitespaceSensitivity: 'css',
  vueIndentScriptAndStyle: false,
};
